/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Java_Ticket_Proyecto;

import static Java_Ticket_Proyecto.Administracion_de_eventos.irA;
import static Java_Ticket_Proyecto.Crear_Evento.eventos;
import static Java_Ticket_Proyecto.Crear_Evento.user;
import static Java_Ticket_Proyecto.Login.usuarioLogin;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author adalb
 */
public class confirmar_evento extends javax.swing.JFrame {

    /**
     * Creates new form confirmar_evento
     */
    public confirmar_evento() {
        initComponents();
    }
    public static int pos=0,tipo=1;
    public static String codigoLogin,mensaje;
    public static Date fecha=Calendar.getInstance().getTime();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CodigoTextbox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Codigo:");

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(CodigoTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodigoTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        codigoLogin=CodigoTextbox.getText();
        boolean noExiste=true;
        if(codigoLogin.isEmpty()){
                JOptionPane.showMessageDialog(null, "Por favor, llenar todos los campos.");
        }else{
            for(int indice=0;indice<eventos.size();indice++){
                if(eventos.get(indice)!=null){ 
                    if(eventos.get(indice).getCodigo().equals(codigoLogin)){
                        if(irA==1){
                            if(eventos.get(indice).getClase()=="Deportivo"){
                                if(user.get(indice).equals(usuarioLogin)){
                                    Evento_Deportivo borrarEvento=new Evento_Deportivo("","cancelado","","",fecha,0,0,
                                        "","","");
                                    eventos.set(indice,borrarEvento);
                                    JOptionPane.showMessageDialog(null, "Ha borrado exitosamente el evento.");
                                    noExiste=false;
                                    break;
                                }else{
                                    JOptionPane.showMessageDialog(null, "Solo el que creo el evento lo puede borrar.");
                                    noExiste=false;
                                    break;
                                }
                          
                            }else if(eventos.get(indice).getClase()=="Musical"){
                                if(user.get(indice).equals(usuarioLogin)){
                                    Evento_Musical borrarEvento=new Evento_Musical("","cancelado","","",fecha,0,0,"");
                                    eventos.set(indice,borrarEvento);
                                    JOptionPane.showMessageDialog(null, "Ha borrado exitosamente el evento.");
                                    noExiste=false;
                                    break;
                                }else{
                                    JOptionPane.showMessageDialog(null, "Solo el que creo el evento lo puede borrar.");
                                    noExiste=false;
                                    break;
                                }
                                
                            }else if(eventos.get(indice).getClase()=="Religioso"){
                                if(user.get(indice).equals(usuarioLogin)){
                                    Evento_Religioso borrarEvento=new Evento_Religioso("","cancelado","","",
                                    fecha,0,0);
                                    eventos.set(indice,borrarEvento);
                                    JOptionPane.showMessageDialog(null, "Ha borrado exitosamente el evento.");
                                    noExiste=false;
                                    break;
                                }else{
                                    JOptionPane.showMessageDialog(null, "Solo el que creo el evento lo puede borrar.");
                                    noExiste=false;
                                    break;
                                }
                                
                            }
                        }else if(irA==2){
                            pos=indice;
                            noExiste=false;
                            if(eventos.get(indice).getClase().equals("Deportivo")){
                                tipo=1;
                            }else if(eventos.get(indice).getClase().equals("Musical")){
                                tipo=2;
                            }else if(eventos.get(indice).getClase().equals("Religioso")){
                                tipo=3;
                            }
                            Editar_Evento pasar=new Editar_Evento();
                            pasar.setVisible(true);
                            this.setVisible(false);
                            break;
                        }else if(irA==3){
                            pos=indice;
                            noExiste=false;
                            JOptionPane.showMessageDialog(null, "Titulo de evento: "+eventos.get(indice).getTitulo()+
                                    "\n"+"Codigo de Evento: "+eventos.get(indice).getCodigo()+", Monto de Evento: "+eventos.get(indice).getMonto()+
                                    "\n"+"Tipo de Evento: "+eventos.get(indice).getClase()+", Personas que asisiteron al evento: "+eventos.get(indice).getCantidad()+
                                    "\n"+"Descripcion del evento: "+eventos.get(indice).getDescripcion()+
                                    "\n"+"Fecha del evento: "+eventos.get(indice).getFecha());
                            break;
                        }
                    }else{
                        //buscara por el evento cancelado
                    }
                }
            }
            if(noExiste==true){
                JOptionPane.showMessageDialog(null, "Este evento no existe.");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Administracion_de_eventos pasar=new Administracion_de_eventos();
        pasar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(confirmar_evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(confirmar_evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(confirmar_evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(confirmar_evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new confirmar_evento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodigoTextbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
