/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Java_Ticket_Proyecto;

import static Java_Ticket_Proyecto.Crear_Usuario.users;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author adalb
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        users.add(new Usuarios("Bryan Banegas","admin","supersecreto",18,1));
    }
    public static Date fecha;
    public static Evento llamar=new Evento("","","","",fecha,0,0);
    public static ArrayList algo=new ArrayList<>();
    public static DefaultListModel modelo=new DefaultListModel();
    public static Calendar hoy=Calendar.getInstance();
    public static Calendar fin=Calendar.getInstance();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventosRealizados = new javax.swing.JButton();
        eventosFuturos = new javax.swing.JButton();
        eventosCancelados = new javax.swing.JButton();
        Ingreso = new javax.swing.JButton();
        PerfilUsuario = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TituloTextBox = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eventosRealizados.setText("Listar eventos realizados");
        eventosRealizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventosRealizadosActionPerformed(evt);
            }
        });
        getContentPane().add(eventosRealizados, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 86, -1, -1));

        eventosFuturos.setText("Listar eventos futuros");
        eventosFuturos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventosFuturosActionPerformed(evt);
            }
        });
        getContentPane().add(eventosFuturos, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 135, -1, -1));

        eventosCancelados.setText("Listar eventos cancelados");
        eventosCancelados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventosCanceladosActionPerformed(evt);
            }
        });
        getContentPane().add(eventosCancelados, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 192, -1, -1));

        Ingreso.setText("Ingreso generado por fecha");
        getContentPane().add(Ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 250, -1, -1));

        PerfilUsuario.setText("Ver Perfil de usuario");
        PerfilUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(PerfilUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 308, -1, -1));

        jButton7.setText("Regresar a Menú Principal");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 381, -1, -1));

        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 206, -1));

        jLabel1.setText("Cantidad de eventos Religiosos:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        jLabel2.setText("Cantidad de eventos Musicales:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        jLabel3.setText("0");
        jLabel3.setText("ehwgjhbksajxnl");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, -1, -1));
        getContentPane().add(TituloTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 70, -1));

        jLabel4.setText("0");
        jLabel3.setText("ehwgjhbksajxnl");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, -1, -1));

        jLabel6.setText("0");
        jLabel3.setText("ehwgjhbksajxnl");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, -1, -1));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, -1, -1));

        jLabel7.setText("Cantidad de eventos Deportivos:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eventosRealizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventosRealizadosActionPerformed
        // TODO add your handling code here:
        TituloTextBox.setText("Lista de eventos realizados:");
        llamar.listaDeEventosRealizados(0);
    }//GEN-LAST:event_eventosRealizadosActionPerformed

    private void eventosFuturosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventosFuturosActionPerformed
        // TODO add your handling code here:
        TituloTextBox.setText("Lista de eventos futuros:");
        llamar.listaDeEventosFuturos(0);
    }//GEN-LAST:event_eventosFuturosActionPerformed

    private void eventosCanceladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventosCanceladosActionPerformed
        // TODO add your handling code here:
        TituloTextBox.setText("Lista de eventos cancelados:");
        TituloTextBox.setText("HOLA MUNDO:)");
    }//GEN-LAST:event_eventosCanceladosActionPerformed

    private void PerfilUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilUsuarioActionPerformed
        // TODO add your handling code here:
        TituloTextBox.setText("Perfil de usuario:");
    }//GEN-LAST:event_PerfilUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ingreso;
    private javax.swing.JButton PerfilUsuario;
    private javax.swing.JLabel TituloTextBox;
    private javax.swing.JButton eventosCancelados;
    private javax.swing.JButton eventosFuturos;
    private javax.swing.JButton eventosRealizados;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
